# Generated by Django 3.2 on 2021-04-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('stage_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6)),
                ('height', models.IntegerField()),
                ('chest', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('butt', models.IntegerField()),
                ('bio', models.TextField()),
                ('photo', models.FileField(null=True, upload_to='model_images/', verbose_name='')),
            ],
            options={
                'db_table': 'ProL Models',
            },
        ),
    ]
