# Generated by Django 3.2 on 2021-05-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='model_images/')),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fmodels.fashionmodel')),
            ],
        ),
    ]
