# Generated by Django 3.2 on 2021-05-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmodels', '0002_fashionmodelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashionmodelimage',
            old_name='images',
            new_name='image',
        ),
    ]
