# Generated by Django 3.2 on 2021-05-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmodels', '0005_alter_fashionmodelimage_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashionmodelimage',
            old_name='model',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='fashionmodelimage',
            old_name='image',
            new_name='picture',
        ),
    ]
