# Generated by Django 3.2 on 2021-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmodels', '0006_auto_20210502_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fashionmodelimage',
            options={'ordering': ['picture']},
        ),
        migrations.AlterField(
            model_name='fashionmodelimage',
            name='picture',
            field=models.FileField(upload_to='model_images/', verbose_name=''),
        ),
        migrations.AlterUniqueTogether(
            name='fashionmodelimage',
            unique_together={('album', 'picture')},
        ),
    ]
