# Generated by Django 3.2 on 2021-05-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmodels', '0007_auto_20210502_2000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fashionmodel',
            table=None,
        ),
    ]
