# Generated by Django 3.2 on 2021-05-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fmodels', '0008_alter_fashionmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fashionmodel',
            table='ProL Models',
        ),
    ]
