# Generated by Django 3.2 on 2021-04-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_publish_now_article_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
